apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-Deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
              - name: client
                image: nomanaadma/multi-worker
                ports:
                    containerPort: 3000